
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace MarathonSkills.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Timesheet
{

    public int IdTimesheet { get; set; }

    public int StaffId { get; set; }

    public System.DateTime StartDateTime { get; set; }

    public System.DateTime EndDateTime { get; set; }

    public decimal PaymentAmount { get; set; }



    public virtual Staff Staff { get; set; }

}

}
